Repository 389ds/389-ds-base, pull requests merged in 2023-08, with the labels that each got.

#5868 Issue 5867 - lib389 should use filter for tarfile as written in PEP 706
  dirsrvtests/tests/tickets/ticket47988_test.py
  src/lib389/lib389/__init__.py
  src/lib389/lib389/tools.py
Labels: lib389, In JIRA

#5879 Issue 5876 - CI Test random failure - Import
  dirsrvtests/tests/suites/import/import_test.py
Labels: CI test

#5849 Issue 5848 - dsconf should prevent setting the replicaID for hub and consumer roles
  dirsrvtests/tests/suites/clu/dsconf_test.py
  src/lib389/lib389/cli_conf/replication.py
Labels: work in progress

#5895 Issue 5894 - lmdb import error fails with Could not store the entry
  ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c
Labels: lmdb

#5881 Issue i5846 - Crash when lmdb import is aborted
  dirsrvtests/tests/suites/import/import_test.py
  ldap/servers/slapd/back-ldbm/db-mdb/mdb_import_threads.c
Labels: bug, lmdb
